cloud-storage e social-news-aggregator atualizados
PrivacidadeDigital/privacidade.digital pull request #64
Opened 2020-09-22 23:34 UTC by jecogeo

Incluído um arquivo badge.html para os botões de política de privacidade e atualizadas as páginas mencionadas no título. Página totalmente funcional.

2020-09-23 02:40 UTC, abbluiz requested changes
Opa, esqueci de te avisar: no Privacidade Digital nós não incluímos links pro fórum do PrivacyTools por ser em Inglês, por enquanto. Então seria legal remover as linhas 13, 26, e 37 no arquivo social-news-aggregator.html e linha 16 em cloud-storage.html.

Por fim, o arquivo priv_dig_wrksp.code-workspace veio do PrivacyTools ou você mesmo criou? Se for algo para o seu desenvolvimento local, deve ser deletado.

Fico no aguardo pelas mudanças e valeu mesmo pela colaboração!

2020-09-23 17:05 UTC, jecogeo reviewed
Modificações no PR atendidas

2020-09-23 19:36 UTC, abbluiz commented
Eu esqueci completamente de verficar a branch na qual você estava trabalhando. As atualizações estão sendo feitas na branch conflitos-pendentes conforme descrito na wiki do repositório.

Não posso aprovar esse PR, porque ele modifica diretamente a branch master. A branch master só é atualizada após todos os conflitos, traduções e revisões são finalizados em conflitos-pendentes.

Perdão por não ter chamado sua atenção sobre o assunto antes de pedir as outras modificações. Estarei fechando esse PR em breve, mas deve ser fácil pra você fazer as mesmas modificações na branch correta e fazer outro PR.

2020-09-23 19:37 UTC, closed without merging

2020-09-24 01:34 UTC, jecogeo commented
Sem problema, vou fazer outra PR no branch certo. Dei uma olhada no https://github.com/PrivacidadeDigital/privacidade.digital/blob/master/.github/CONTRIBUTING.md#criando-pull-requests e não menciona nada lá sobre isso. Dei uma vasculhada geral, mas não encontrei. Caso esteja mencionado em outro lugar da wiki, talvez fosse interessante colocar essa informação nesta seção, que é onde vamos olhar para contribuir. Mas de boa, amanhã faço uma nova! 😉

2020-09-24 01:38 UTC, abbluiz commented
Acho que você tem razão quanto a não estar muito clara essa informação. Vou atualizar o CONTRIBUTING.md hoje mesmo.

Mas esse seria o ponto de partida sobre o assunto: https://github.com/PrivacidadeDigital/privacidade.digital/wiki/Ciclo-b%C3%A1sico-de-desenvolvimento

2020-09-24 01:57 UTC, jecogeo commented
Nossa, não sei como passei batido por isso... valeu por indicar!